### ISSUE TITLE
ListFiles code's .open("/") does not work on root, no dir or file seen

### ISSUE THREAD

**Issue by RaphTronic** [Seeed-Studio/Seeed_Arduino_FS#14]
The **ListFiles** example in this library **does not show any file in the root directory** despite a handful of .txt and .pdf files being present.

The output is simply:
13:28:36.861 -> Initializing SD card...
13:28:36.900 -> initialization done.
13:28:36.900 ->   -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
13:28:36.900 -> done!

Same issue with both the **SD_Test** and **ReadWrite** examples. Their tests (create a file, delete, etc) all work except for their **listDir** and **printDirectory** subs that, like in the **ListFiles** example, do not output anything (no file or dir detected).

The problem happens on:   **File root = DEV.open("/");**
Which always returns 'empty' (false). So openNextFile does not work, no files are returned.
Instead of "/" for root I also tried "", "//", "0", "0:", "0:/", "0://", "root", etc. Unsuccesfully.

However, if a TESTDIR directory exists, DEV.open("/TESTDIR") works and returns true, and openNextFile properly returns files.

Looks like a library issue with **.open("/")**

**--> How can the list of files in root be retrieved on a WIO terminal ?**

Setup: _WIO Terminal, FAT32 16GB card, Arduino IDE 2.2.1, Seeed SAMD Board library 1.8.5, Windows 10_

Note: _a similar issue is posted on seeed's forum as well: https://forum.seeedstudio.com/t/on-wio-terminal-i-am-unable-to-open-the-root-directory-on-an-sd-card/275254/3 ._

**Comment by fbeleznay** [comment]
Can I please ask about the progress of this? It still does not work for me.

**Comment by LynnL4** [comment]
Hi， 

I have already fixed this issue in the following commit:  
https://github.com/Seeed-Studio/Seeed_Arduino_FS/commit/2e08a18819a43adeaf470ef0c2ec70cf1dd5d0b2. 

Please test it and let me know if you encounter any further issues. Thanks!

**Comment by fbeleznay** [comment]
I am not sure what I do wrong, but your example code listfiles.ino still does not work for me.
I downloaded and installed this library, I checked that it has the code you mentioned in your fix.
This is the output I get:

Initializing SD card...
initialization done.
  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
done!

I got this output even after I successfully ran the example code that created (and read back) the hello.txt file in the root directory.

I also checked what happens when I change `File root = DEV.open("/");` to `File root = DEV.open("/temp");` (where temp is an existing directory on the SD card). I got the correct file list.

I then tried `File root = DEV.open("/tem/..");` and this gave me the correct list in the root folder.

However, `File root = DEV.open("/");` still gives an empty list.

Am I missing something?
I also found an [older thread](https://forum.seeedstudio.com/t/sd-card-read-problem-on-wio-terminal/254577), where uncommenting `//#ifdef USESPIFLASH` was mentioned in line 30 of listfiles.ino, but I guess, the code changed since that answer, since there is no such code to uncomment.

**Comment by LynnL4** [comment]
Hi, @fbeleznay 
Sorry, it looks like the code sequence was accidentally changed when I submitted the code last time. I have resubmitted it. I tested it on the Wio Terminal (it seems unrelated to the hardware), and this is the result from executing listfiles.ino. Everything looks normal.
![image](https://github.com/user-attachments/assets/43fecfa7-c431-4136-8ff8-2a4909609d42)
Also, could you confirm whether the updated libraries are working properly?
![image](https://github.com/user-attachments/assets/cabf130c-b5f0-4a0b-83d8-0ddf3721139c)
